### ISSUE TITLE
Incorrect type for `limit` parameter in `cisco.catalystcenter.network_devices_info` module

### ISSUE THREAD

**Issue by a-ts** [cisco-en-programmability/catalystcenter-ansible#8]
Hi team,

I encountered a type mismatch issue when using the `cisco.catalystcenter.network_devices_info` module. The `limit` parameter is currently defined as a `float`, but it should be an `int`. This causes the following error during execution:

```
Unexpected failure during module execution: We were expecting to receive an instance of one of the following types: 'int' or 'None'; but instead we received 10.0 which is a 'float'.
```

### Environment

- **Python version:** 3.11.11  
- **Ansible version:** 2.18.6  
- **Catalyst SDK version:** `catalystcentersdk 2.3.7.9.5` 
- **Catalyst collection version:** `cisco.catalystcenter 2.1.4`

### Minimal Playbook to Reproduce

```yaml
- name: Query Cisco Catalyst Center
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Retrieve network devices
      cisco.catalystcenter.network_devices_info:
        _host: "{{ _host }}"
        _username: "{{ _username }}"
        _password: "{{ _password }}"
        _verify: "{{ _verify }}"
        _api_port: "{{ _api_port }}"
        _version: "{{ _version }}"
        _debug: "{{ _debug }}"
        family: Switches and Hubs
        limit: 10
```

### Workaround

I was able to fix the issue locally by modifying the module’s `argument_spec` and changing the type of `limit` from `float` to `int`.

### Request

Could you confirm whether this is a bug or an intentional design choice? If it’s a bug, would you consider updating the module definition accordingly?

Let me know if you need any additional logs, environment details, or testing help.
